---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service

spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30002

  selector:
    type: ci-cd

...
